#include "p24FJ64GA002.h"

_CONFIG1( JTAGEN_OFF & GCP_OFF & GWRP_OFF & BKBUG_OFF
	 & COE_OFF & ICS_PGx1& FWDTEN_OFF )
_CONFIG2( IESO_OFF & FNOSC_FRCPLL & FCKSM_CSDCMD
	 & OSCIOFNC_OFF & IOL1WAY_OFF & I2C1SEL_PRI & POSCMOD_NONE)

int main(void){
    CLKDIV = 0;
    TRISB = 0x00FF;
    CNPU2=0x0080;
    while(1){
	LATBbits.LATB15  = PORTBbits.RB7;
    }
}

